#!/usr/bin/env bash
# scripts/dev/sync-paios-skills.sh
#
# Sync paiOS agent skills from SSoT (.agents/skills/) to all tool adapters:
#   - .claude/skills/   (Claude Code — native skills/ support)
#   - .cursor/skills/   (Cursor — native skills/ support)
#   - .codex/rules/     (Codex CLI — no skills/ system; content embedded into rules file)
#
# Run this after editing any file under .agents/skills/.
#
# Usage: bash scripts/dev/sync-paios-skills.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="${ROOT}/.agents/skills"
SKILLS=(paios-implement paios-review paios-code-health paios-loop)
NATIVE_DESTS=("${ROOT}/.claude/skills" "${ROOT}/.cursor/skills")
CODEX_RULES="${ROOT}/.codex/rules/paiOS.rules"

# --- Verify sources ---
echo "[sync] Verifying skill sources..."
for skill in "${SKILLS[@]}"; do
  if [ ! -f "${SRC}/${skill}/SKILL.md" ]; then
    echo "[sync] ERROR: missing ${SRC}/${skill}/SKILL.md" >&2
    exit 1
  fi
  echo "[sync]   found: ${skill}"
done

# --- Claude Code + Cursor (native skills/ directory) ---
echo "[sync] Syncing to native skills adapters (.claude/skills, .cursor/skills)..."
for dest in "${NATIVE_DESTS[@]}"; do
  mkdir -p "${dest}"
  for skill in "${SKILLS[@]}"; do
    if [ -z "${skill}" ] || [ -z "${dest}" ]; then
      echo "[sync] ERROR: empty skill or dest path" >&2
      exit 1
    fi
    rm -rf "${dest}/${skill}"
    cp -r "${SRC}/${skill}" "${dest}/${skill}"
    echo "[sync]   ${SRC}/${skill} -> ${dest}/${skill}"
  done
done

# --- Codex (no skills/ system — embed all skill content into a single rules file) ---
echo "[sync] Building Codex rules from skill content..."
mkdir -p "$(dirname "${CODEX_RULES}")"

cat > "${CODEX_RULES}" <<'HEADER'
# paiOS Codex Rules
# Auto-generated by scripts/dev/sync-paios-skills.sh — do NOT edit directly.
# Edit .agents/skills/<skill>/SKILL.md and re-run the sync script.
#
# Codex does not support a separate skills/ directory, so all skill content
# is embedded here as named sections.
#
# Primary context: AGENTS.md
# Architecture:    docs/src/content/docs/architecture/
# Rust style:      docs/src/content/docs/guides/contributing/rust-style.mdx

HEADER

for skill in "${SKILLS[@]}"; do
  skill_file="${SRC}/${skill}/SKILL.md"
  echo "" >> "${CODEX_RULES}"
  echo "# ============================================================" >> "${CODEX_RULES}"
  echo "# SKILL: ${skill}" >> "${CODEX_RULES}"
  echo "# ============================================================" >> "${CODEX_RULES}"
  # Strip YAML frontmatter (--- ... ---) and the SSoT comment line before embedding
  awk '
    BEGIN { in_front=0; done_front=0 }
    /^---$/ && !done_front { in_front=!in_front; if(!in_front) done_front=1; next }
    in_front { next }
    /^<!-- SSoT:/ { next }
    { print }
  ' "${skill_file}" >> "${CODEX_RULES}"
done

echo "[sync] Codex rules written to ${CODEX_RULES}"

echo "[sync] Done. Skills synced to:"
for dest in "${NATIVE_DESTS[@]}"; do
  echo "  ${dest}/"
done
echo "  ${CODEX_RULES} (embedded)"
